# Generated by Django 5.1.5 on 2025-08-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Note', '0002_delete_note_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('nt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nt_title', models.CharField(max_length=100)),
                ('nt_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('nt_content', models.TextField(blank=True, null=True)),
                ('nt_img', models.CharField(blank=True, max_length=255, null=True)),
                ('nt_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('nt_date', models.DateTimeField()),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Note.user')),
            ],
        ),
    ]
