# Generated by Django 5.2 on 2025-08-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='us',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='st',
        ),
        migrations.RemoveField(
            model_name='task',
            name='us',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ws',
        ),
        migrations.RemoveField(
            model_name='usedtask',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='usedtask',
            name='us',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='us',
        ),
        migrations.DeleteModel(
            name='InSpace',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='UsedTask',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WorkSpace',
        ),
    ]
