# Generated by Django 5.1.5 on 2025-08-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0002_remove_subtask_ts_remove_subtask_us_remove_todo_st_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ts_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts_title', models.CharField(max_length=100)),
                ('ts_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('ts_status', models.BooleanField(default=False)),
                ('ts_start', models.DateField()),
                ('ts_end', models.DateField()),
                ('ts_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('st_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('st_title', models.CharField(max_length=100)),
                ('st_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('st_note', models.TextField(blank=True, null=True)),
                ('st_status', models.BooleanField(default=False)),
                ('st_start', models.DateField()),
                ('st_end', models.DateField()),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.user')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('td_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('td_type', models.CharField(max_length=100)),
                ('td_status', models.BooleanField(default=False)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.subtask')),
                ('ts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
        ),
        migrations.CreateModel(
            name='UsedTask',
            fields=[
                ('ut_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.user'),
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('ws_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ws_name', models.CharField(max_length=100)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='ws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.workspace'),
        ),
        migrations.CreateModel(
            name='InSpace',
            fields=[
                ('is_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_role', models.CharField(max_length=50)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.user')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.workspace')),
            ],
        ),
    ]
