# Generated by Django 5.1.5 on 2025-10-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ts_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts_title', models.CharField(max_length=100)),
                ('ts_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('ts_status', models.IntegerField(default=False)),
                ('ts_start', models.DateField()),
                ('ts_end', models.DateField()),
                ('ts_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_img', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('st_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('st_title', models.CharField(max_length=100)),
                ('st_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('st_note', models.TextField(blank=True, null=True)),
                ('st_status', models.BooleanField(default=False)),
                ('st_start', models.DateField()),
                ('st_end', models.DateField()),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.task')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('td_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('td_type', models.CharField(max_length=100)),
                ('td_status', models.BooleanField(default=False)),
                ('st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Common.subtask')),
                ('ts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Common.task')),
            ],
        ),
        migrations.CreateModel(
            name='UsedTask',
            fields=[
                ('ut_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.task')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('nt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nt_title', models.CharField(max_length=100)),
                ('nt_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('nt_content', models.TextField(blank=True, null=True)),
                ('nt_img', models.CharField(blank=True, max_length=255, null=True)),
                ('nt_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('nt_date', models.DateTimeField()),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('ht_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_output', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fb_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_text', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_otp', models.CharField(max_length=20)),
                ('vc_start', models.DateTimeField()),
                ('vc_end', models.DateTimeField()),
                ('vc_status', models.BooleanField(default=False)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('ws_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ws_name', models.CharField(max_length=100)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='ws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Common.workspace'),
        ),
        migrations.CreateModel(
            name='InSpace',
            fields=[
                ('is_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_role', models.CharField(max_length=50)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.workspace')),
            ],
        ),
    ]
