# Generated by Django 5.1.5 on 2025-09-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Common.workspace'),
        ),
    ]
