# Generated by Django 5.1.5 on 2025-09-19 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_alter_task_ws'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fb_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_text', models.TextField()),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.user')),
            ],
        ),
    ]
