# Generated by Django 5.1.5 on 2025-09-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_feedback_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ai_output',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
    ]
