# Generated by Django 5.1.5 on 2025-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_alter_history_ai_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
