# Generated by Django 5.1.5 on 2025-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_alter_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ts_status',
            field=models.IntegerField(default=False),
        ),
    ]
