# Generated by Django 5.2.6 on 2025-10-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0006_alter_task_ts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='vc_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vc_start',
            field=models.DateTimeField(),
        ),
    ]
