# Generated by Django 5.2.6 on 2025-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0007_alter_verification_vc_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
