# Generated by Django 5.1.5 on 2025-08-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_otp', models.CharField(max_length=20)),
                ('vc_start', models.DateField()),
                ('vc_end', models.DateField()),
                ('vc_status', models.BooleanField(default=False)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
